services:
  - type: web
    name: cybershield-backend
    runtime: python
    pythonVersion: "3.12.4"
    region: oregon
    plan: free
    buildCommand: "pip install -r cybershield/backend/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    workingDir: cybershield/backend
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BACKEND_URL
        value: "https://final-year-project-id8d.onrender.com"
      - key: FRONTEND_URL
        value: "https://final-year-project-fjgf.vercel.app"
      - key: GOOGLE_REDIRECT_URI
        value: "https://final-year-project-id8d.onrender.com/api/v1/auth/oauth/google/callback"
      - key: GITHUB_REDIRECT_URI
        value: "https://final-year-project-id8d.onrender.com/api/v1/auth/oauth/github/callback"
    autoDeploy: true