"""
Audit action constants for logging user activities.
"""

# Authentication Actions
LOGIN = "LOGIN"
LOGOUT = "LOGOUT"
FAILED_LOGIN = "FAILED_LOGIN"
PASSWORD_CHANGE = "PASSWORD_CHANGE"

# Scanner Actions
SCAN_STARTED = "SCAN_STARTED"
SCAN_COMPLETED = "SCAN_COMPLETED"
REPOSITORY_SCAN = "REPOSITORY_SCAN"
SECURITY_SCAN = "SECURITY_SCAN"

# Quiz Actions
QUIZ_STARTED = "QUIZ_STARTED"
QUIZ_COMPLETED = "QUIZ_COMPLETED"

# OWASP Actions
OWASP_SIMULATION_STARTED = "OWASP_SIMULATION_STARTED"
OWASP_SIMULATION_COMPLETED = "OWASP_SIMULATION_COMPLETED"

# Report Actions
REPORT_DOWNLOADED = "REPORT_DOWNLOADED"

# Profile Actions
PROFILE_UPDATED = "PROFILE_UPDATED"

# Module Names
AUTH = "AUTH"
GITHUB_SCANNER = "GITHUB_SCANNER"
SECURITY_SCANNER = "SECURITY_SCANNER"
QUIZ = "QUIZ"
OWASP = "OWASP"
REPORTS = "REPORTS"
PROFILE = "PROFILE"

# Status Values
SUCCESS = "SUCCESS"
FAILED = "FAILED"